version: '3'
services:

  url-sh:
    build: .
    ports:
      - "8080:8080"
      
  db:
    image: mysql:8.0.28
    ports:
    - "3306:3306"
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw
    - MYSQL_PASSWORD=my-secret-pw

