apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2022-01-25T16:00:48Z","reason":"SucceededGetScale","message":"the
      HPA controller was able to get the target''s current scale"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2022-01-25T16:00:48Z"}]'
  name: url-sh
  namespace: default
spec:
  maxReplicas: 6
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url-sh
  targetCPUUtilizationPercentage: 50
  
status:
  currentReplicas: 2
  desiredReplicas: 0
